language: cpp
sudo: require
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - make
      - cmake
      - g++
      - gcc
      - automake
      - autoconf
      - libtool

compiler:
  - clang
  - gcc

before_install:
  - git clone https://github.com/skymizer/SkyPat.git
  - cd SkyPat
  - ./autogen.sh
  - ./configure
  - make
  - sudo make install
  - cd ..

script: 
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - ./test/unittests/test_operator_add