language: cpp
install: cmake make
sudo: require
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - make
      - cmake
      - g++
      - gcc
      - automake

compiler:
  - clang
  - gcc

script: 
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - ctest